package:
  name: cylc
  version: 8.0.0

source:
  fn: cylc-ui-8.0.0.tar.gz
  url: https://github.com/cylc/cylc-ui/archive/0.5.tar.gz
  md5: 9bc19912e125fbf93bd3049fb13d9b7c

requirements:
  build:
    - nodejs >= 12.0

  run:
    - python >= 3.7

about:
  home: https://cylc.github.io
  license: GPL-3.0
